apiVersion: v1
kind: Pod
metadata:
  name: nginx-tolerated
spec:
  containers:
  - name: nginx
    image: nginx
#it automatically opens port number 80
  tolerations:
  - key: "project"
    operator: "Equal"
    value: "roboshop"
    effect: "NoSchedule"